# Generated by Django 4.2.30 on 2026-06-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=3)),
                ('quote', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('date', models.DateField()),
                ('source', models.CharField(default='ECB', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'base', 'quote'],
                'indexes': [models.Index(fields=['base', 'quote', 'date'], name='marketdata__base_a7d42d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='fxrate',
            constraint=models.UniqueConstraint(fields=('base', 'quote', 'date', 'source'), name='unique_rate_per_pair_date'),
        ),
    ]
