# Generated by Django 4.2.30 on 2026-06-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('source', models.CharField(default='yfinance', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'ticker'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='fxrate',
            name='unique_rate_per_pair_date',
        ),
        migrations.AddConstraint(
            model_name='fxrate',
            constraint=models.UniqueConstraint(fields=('base', 'quote', 'date'), name='unique_rate_per_pair_date'),
        ),
        migrations.AddIndex(
            model_name='assetprice',
            index=models.Index(fields=['ticker', 'date'], name='marketdata__ticker_1d995a_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetprice',
            constraint=models.UniqueConstraint(fields=('ticker', 'date', 'source'), name='unique_price_per_ticker_date'),
        ),
    ]
