# Generated by Django 6.0.6 on 2026-06-08 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CHF', 'CHF'), ('GBP', 'GBP')], default='CHF', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('listed_equity', 'Listed Equity'), ('etf', 'ETF'), ('bond', 'Bond'), ('cash', 'Cash'), ('real_estate', 'Real Estate'), ('private_holding', 'Private Holding'), ('other', 'Other')], default='listed_equity', max_length=20)),
                ('ticker', models.CharField(blank=True, default='', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CHF', 'CHF'), ('GBP', 'GBP')], default='USD', max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('manual_current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.portfolio')),
            ],
        ),
    ]
