# Generated by Django 4.2.30 on 2026-07-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
